// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:quizlone/models/match_record.dart';
import 'package:quizlone/models/study_group.dart';
import 'package:quizlone/models/study_list.dart';
import 'package:quizlone/models/term.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MatchRecordAdapter());
    registerAdapter(StudyGroupAdapter());
    registerAdapter(StudyListAdapter());
    registerAdapter(TermAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MatchRecordAdapter());
    registerAdapter(StudyGroupAdapter());
    registerAdapter(StudyListAdapter());
    registerAdapter(TermAdapter());
  }
}
