-keep class io.flutter.util.PathUtils { *; }
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class com.google.dart.jni.** { *; }
